CONNECTION_URL=jdbc:mysql://127.0.0.1:3306/hstrain
LOGIN_USER=login
LOGIN_PASS=login
ACQUIRENTE_USER=acquirente
ACQUIRENTE_PASS=acquirente
LAVORATORE_USER=lavoratore
LAVORATORE_PASS=lavoratore
GESTORESERVIZIO_USER=gestore_servizio
GESTORESERVIZIO_PASS=gestore_servizio